export const products = [
    {
      companyName: "Willys",
      Product: "Bread",
      Price1: "40kr",
      Price:"20kr",
      ExpiryDate: "Expiry Date:25-11",
      Address: "Address:Knivsta",
      id:"1",
      caption:"Icon1",
      icon:"video/coop2.webp",
      Img:"12345",
    },
    {
      companyName:"Coop",
      Product: "Bread",
      Price1: "40kr",
      Price:"20kr",
      ExpiryDate:"Expiry Date:25-11",
      Address: "Address:Uppsala",
      Img:"12345",
    },
    {
      companyName:"LideL",
      Product:"Bread",
      Price1: "40kr",
      Price:"20kr",
      ExpiryDate: "Expiry Date :25-11",
      Address: "Address:Stockholm",
      Img:"12345",
    },
    {
        companyName:"ICA",
        Product: "Bread",
        Price1: "40kr",
        Price:"20kr",
        ExpiryDate: "Expiry Date:25-11",
        Address: "Address :Märsta",
        Img:"12345",
      },
      {
        companyName:"Willys",
        Product: "Bread",
        Price1:"40kr",
        Price:"20kr",
        ExpiryDate: "Expiry Date:25-11",
        Address: "Address:Knivsta",
        Img:"12345",
      },
      {
        companyName:"Coop",
        Product: "Bread",
        Price1: "40kr",
        Price:"20kr",
        ExpiryDate:"Expiry Date :25-11",
        Address: "Address:Uppsala",
        Img:"12345",
      },

  ];
  